# Application properties
server.port=1406
spring.application.name=UnifiedWorkflowApplication

# TemporalConstants properties
spring.temporal.namespace=default
spring.temporal.connection.target=localhost:7233

# Workflow Orchestration
spring.temporal.workers[0].task-queue=workflow-orchestration-queue
spring.temporal.workers[0].workflowClasses[0]=com.innodata.platform.automation.orchestrator.workflow.WorkflowOrchestratorImpl
spring.temporal.workers[0].activityBeans[0]=contentActivitiesImpl
spring.temporal.workers[0].activityBeans[1]=emailActivitiesImpl
spring.temporal.workers[0].activityBeans[2]=ticketActivitiesImpl